### ISSUE TITLE
3d evaluate result is wrong?

### ISSUE THREAD

**Issue by LordonCN** [shangjie-li/ldf_kitti_object_eval_python#1]
Please Help

https://github.com/traveller59/kitti-object-eval-python/issues/21

**Comment by shangjie-li** [comment]
This code is designed to evaluate accuracy at different distances. If you want to evaluate accuracy with KITTI's official metrics (Easy, Moderate, Hard), do not use the --use_ldf_eval option.

**Comment by LordonCN** [comment]
I know this but when I evaluate two same results use this tool, its evaluate result is wrong?

```
Car AP:
bbox (0.70): 100.0000, 100.0000, 100.0000
bev  (0.70): 0.0690, 0.1094, 0.1963
3d   (0.70): 0.0690, 0.1094, 0.1963
aos        : 100.0000, 100.0000, 100.0000

Car AP:
bbox (0.70): 100.0000, 100.0000, 100.0000
bev  (0.50): 0.0690, 0.1094, 0.1963
3d   (0.50): 0.0690, 0.1094, 0.1963
aos        : 100.0000, 100.0000, 100.0000

Car AP:
bbox (0.70): 100.0000, 100.0000, 100.0000
bev  (0.25): 7.8261, 10.0645, 16.0457
3d   (0.25): 7.8261, 10.0645, 16.0457
aos        : 100.0000, 100.0000, 100.0000
```

**Comment by LordonCN** [comment]
> I know this but when I evaluate two same results use this tool, its evaluate result is wrong?
> 
> ```
> Car AP:
> bbox (0.70): 100.0000, 100.0000, 100.0000
> bev  (0.70): 0.0690, 0.1094, 0.1963
> 3d   (0.70): 0.0690, 0.1094, 0.1963
> aos        : 100.0000, 100.0000, 100.0000
> 
> Car AP:
> bbox (0.70): 100.0000, 100.0000, 100.0000
> bev  (0.50): 0.0690, 0.1094, 0.1963
> 3d   (0.50): 0.0690, 0.1094, 0.1963
> aos        : 100.0000, 100.0000, 100.0000
> 
> Car AP:
> bbox (0.70): 100.0000, 100.0000, 100.0000
> bev  (0.25): 7.8261, 10.0645, 16.0457
> 3d   (0.25): 7.8261, 10.0645, 16.0457
> aos        : 100.0000, 100.0000, 100.0000
> ```

I think bev and 3d result should also be 100, this result confuses me a lot.

**Comment by shangjie-li** [comment]
I'm not sure if your result files are in the format KITTI requires. You might want to try "python evaluate.py --result_dir=kitti/training/label_2 --label_dir=kitti/training/label_2" to see if all the results are 100.

**Comment by LordonCN** [comment]
> I'm not sure if your result files are in the format KITTI requires. You might want to try "python evaluate.py --result_dir=kitti/training/label_2 --label_dir=kitti/training/label_2" to see if all the results are 100.

I copy training label to result_dir and add score(0.95) to each file in result_dir, it looks like :
```
000001.txt
gt: 
Truck 0.00 0 -1.57 599.41 156.40 629.75 189.25 2.85 2.63 12.34 0.47 1.49 69.44 -1.56
dt: 
Truck 0.00 0 -1.57 599.41 156.40 629.75 189.25 2.85 2.63 12.34 0.47 1.49 69.44 -1.56 0.95
```
The evaluate result is:
```
Car AP(Average Precision)@0.70, 0.70, 0.70:
bbox AP:100.00, 100.00, 100.00
bev  AP:0.07, 0.11, 0.20
3d   AP:0.07, 0.11, 0.20
aos  AP:100.00, 100.00, 100.00
Car AP(Average Precision)@0.70, 0.50, 0.50:
bbox AP:100.00, 100.00, 100.00
bev  AP:0.07, 0.11, 0.20
3d   AP:0.07, 0.11, 0.20
aos  AP:100.00, 100.00, 100.00
Pedestrian AP(Average Precision)@0.50, 0.50, 0.50:
bbox AP:100.00, 100.00, 100.00
bev  AP:0.18, 0.24, 0.30
3d   AP:0.18, 0.24, 0.30
aos  AP:100.00, 100.00, 100.00
Pedestrian AP(Average Precision)@0.50, 0.25, 0.25:
bbox AP:100.00, 100.00, 100.00
bev  AP:11.99, 15.32, 17.74
3d   AP:11.99, 15.32, 17.74
aos  AP:100.00, 100.00, 100.00
Cyclist AP(Average Precision)@0.50, 0.50, 0.50:
bbox AP:100.00, 100.00, 100.00
bev  AP:0.03, 0.08, 0.09
3d   AP:0.03, 0.08, 0.09
aos  AP:100.00, 100.00, 100.00
Cyclist AP(Average Precision)@0.50, 0.25, 0.25:
bbox AP:100.00, 100.00, 100.00
bev  AP:11.44, 15.06, 16.05
3d   AP:11.44, 15.06, 16.05
aos  AP:100.00, 100.00, 100.00
```

**Comment by shangjie-li** [comment]
> 

This command won't work, sorry.

**Comment by shangjie-li** [comment]
> I'm not sure if your result files are in the format KITTI requires. You might want to try "python evaluate.py --result_dir=kitti/training/label_2 --label_dir=kitti/training/label_2" to see if all the results are 100.

This command doesn't work, sorry.

**Comment by shangjie-li** [comment]
I tried the same thing as you did and got similar results. Now I understand your question about BEV AP and 3D AP. To figure this out, I tried to print some overlap calculation results in the 'bev_box_overlap' and 'd3_box_overlap' functions in 'eval.py'. I found that when gt and dt are the same, BEV overlap and 3D overlap are almost zero. However, if I modify dt slightly, for example by increasing the X coordinate by a small amount, the BEV overlap and 3D overlap will not be 0. I think there are some bugs in the internal implementation of these two functions.

**Comment by shangjie-li** [comment]
In general, the results predicted by the network are unlikely to be exactly the same as the labels. So this code should work.

**Comment by LordonCN** [comment]
> I tried the same thing as you did and got similar results. Now I understand your question about BEV AP and 3D AP. To figure this out, I tried to print some overlap calculation results in the 'bev_box_overlap' and 'd3_box_overlap' functions in 'eval.py'. I found that when gt and dt are the same, BEV overlap and 3D overlap are almost zero. However, if I modify dt slightly, for example by increasing the X coordinate by a small amount, the BEV overlap and 3D overlap will not be 0. I think there are some bugs in the internal implementation of these two functions.

In fact, if the prediction is accurate enough,  dt will definitely approach gt. I have also debugged this part of the code but it has not been resolved, I wonder can this code explain the true level of the paper？

**Comment by shangjie-li** [comment]
According to my experience, KITTI's official evaluation results are basically consistent with this code. [Here](https://ieeexplore.ieee.org/abstract/document/10097572) is my paper, although the results in the paper are not very good.
